name: nightly-build
on: [push]
jobs:
  test-github-actions-locally:
    runs-on: ubuntu-latest
    name: run sample test locally
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: npm ci
      - name: Check xo-lint formatter
        run: npm run xo
      - name: validate-fs
        uses: ./
        id: validation
        with:
          brace-expansion: "{x,{a,b/{ba1,ba2,bb1,bb2},c,d}/{a.qa.config,b.prd.config}}"
          ignore-files: "README.md"
          ignore-directories: ".git"
          read-path: "./sample_folder"
          render-layout: "vertical"
