name: release-test
on:
  schedule:
    - cron:  '0 9 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate
        uses: anyone-developer/anyone-validate-fs@main
        with:
          brace-expansion: "{a,b/{ba1,ba2,bb1,bb2},c,d}/{a.qa.config,b.prd.config}"
          ignore-files: 'README.md'
          ignore-directories: ''
          read-path: './sample_folder'
          render-layout: 'vertical'
