name: unit-test
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: run unit test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test
